In [76]:
import tensorflow as tf

In [82]:
x = tf.constant([[1., 4., 2.],
                 [4., 6., 3.],
                 [2., 3., 4.]])
#x = tf.constant([[1., 2., 3.],
#                 [4., 6., 5.]])

In [83]:
print(f'\nx:\n{x}')
c0 = tf.concat([x, x, x], axis=0)
print(f'\ntf.concat([x, x, x], axis=0):\n {c0}')
c1 = tf.concat([x, x, x], axis=1)
print(f'\ntf.concat([x, x, x], axis=1):\n {c1}')


x:
[[1. 4. 2.]
 [4. 6. 3.]
 [2. 3. 4.]]

tf.concat([x, x, x], axis=0):
 [[1. 4. 2.]
 [4. 6. 3.]
 [2. 3. 4.]
 [1. 4. 2.]
 [4. 6. 3.]
 [2. 3. 4.]
 [1. 4. 2.]
 [4. 6. 3.]
 [2. 3. 4.]]

tf.concat([x, x, x], axis=1):
 [[1. 4. 2. 1. 4. 2. 1. 4. 2.]
 [4. 6. 3. 4. 6. 3. 4. 6. 3.]
 [2. 3. 4. 2. 3. 4. 2. 3. 4.]]


In [84]:
print(f'\nx:\n{x}')
rt = tf.reduce_sum(x)
print(f'\ntf.reduce_sum(x):\n {rt}')
r0 = tf.reduce_sum(x[0])
print(f'\ntf.reduce_sum(x[0]):\n {r0}')


x:
[[1. 4. 2.]
 [4. 6. 3.]
 [2. 3. 4.]]

tf.reduce_sum(x):
 29.0

tf.reduce_sum(x[0]):
 7.0


In [85]:
print(f'\nx:\n{x}')
s1 = tf.nn.softmax(x, axis=1)
print(f'\ntf.nn.softmax(x, axis=1): \n {s1}')
rx = tf.reduce_sum(x[0])
print(f'\ntf.reduce_sum(x[0]): {rx}')
s0 = tf.nn.softmax(x, axis=0)
print(f'\ntf.nn.softmax(x, axis=0):\n {s0}')
rty = tf.reduce_sum(tf.transpose(y)[0])
print(f'\ntf.reduce_sum(tf.transpose(y)[0]): {rty}')


x:
[[1. 4. 2.]
 [4. 6. 3.]
 [2. 3. 4.]]

tf.nn.softmax(x, axis=1): 
 [[0.04201007 0.8437947  0.11419519]
 [0.11419519 0.8437947  0.04201007]
 [0.09003057 0.24472848 0.66524094]]

tf.reduce_sum(x[0]): 7.0

tf.nn.softmax(x, axis=0):
 [[0.04201007 0.11419519 0.09003057]
 [0.8437947  0.8437947  0.24472848]
 [0.11419519 0.04201007 0.66524094]]

tf.reduce_sum(tf.transpose(y)[0]): 1.0
